name: Upload Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Create dummy file
        run: |
          mkdir -p dummy
          echo "Hello World" > dummy/test.txt

      - name: Upload dummy file
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: dummy/test.txt
